### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhaosq2016** [smithlabcode/ribotricer#11]
* ribotricer version:1.3.2
* Python version: 3.6
* Operating System: Ubuntu18.04

### Description

I installed ribotricer on conda according to the installation command you gave. But when I run “ribotricer --help”， I got an error.

### What I Did

```
conda create -n ribotricer_env -c bioconda ribotricer
conda activate ribotricer_env
ribotricer --help
```
**The error message is as follows:**
```
Traceback (most recent call last):
  File "miniconda3/envs/ribotricer_env/bin/ribotricer", line 10, in <module>
    sys.exit(cli())
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 809, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 496, in get_help
    return self.command.get_help(self)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click_help_colors/core.py", line 53, in get_help
    self.format_help(ctx, formatter)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 843, in format_help
    self.format_usage(ctx, formatter)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click/core.py", line 782, in format_usage
    formatter.write_usage(ctx.command_path, ' '.join(pieces))
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click_help_colors/core.py", line 23, in write_usage
    colorized_prefix = _colorize(prefix, color=self.headers_color)
  File "/home/zsq/miniconda3/envs/ribotricer_env/lib/python3.6/site-packages/click_help_colors/utils.py", line 14, in _colorize
    return '\033[%dm' % (_ansi_colors[color]) + text + _ansi_reset_all
TypeError: tuple indices must be integers or slices, not str
```

**Comment by zhaosq2016** [comment]
When conda is installed by default, there is a problem with the click version.
